onlyBuiltDependencies:
  - '@evilmartians/lefthook'

neverBuiltDependencies:
  - msw

# Wil come back after because oxlint version is new
# minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - '@rsbuild/core@2.0.12'
  - '@rspack/binding-darwin-arm64@2.0.8'
  - '@rspack/binding-darwin-x64@2.0.8'
  - '@rspack/binding-linux-arm64-gnu@2.0.8'
  - '@rspack/binding-linux-arm64-musl@2.0.8'
  - '@rspack/binding-linux-x64-gnu@2.0.8'
  - '@rspack/binding-linux-x64-musl@2.0.8'
  - '@rspack/binding-wasm32-wasi@2.0.8'
  - '@rspack/binding-win32-arm64-msvc@2.0.8'
  - '@rspack/binding-win32-ia32-msvc@2.0.8'
  - '@rspack/binding-win32-x64-msvc@2.0.8'
  - '@rspack/binding@2.0.8'
  - '@rspack/core@2.0.8'

allowBuilds:
  '@evilmartians/lefthook': true
  msw: true
